# Generated by Django 5.1.7 on 2025-03-30 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In Process', 'In Process'), ('Converted', 'Converted'), ('Recycled', 'Recycled'), ('Dead', 'Dead')], max_length=100)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('lead_source', models.CharField(choices=[('Cold Call', 'Cold Call'), ('Existing Customer', 'Existing Customer'), ('Self Generated', 'Self Generated'), ('Employee', 'Employee'), ('Partner', 'Partner'), ('Public Relations', 'Public Relations'), ('Direct Mail', 'Direct Mail'), ('Conference', 'Conference'), ('Trade Show', 'Trade Show'), ('Web Site', 'Web Site'), ('Word of mouth', 'Word of mouth'), ('Email', 'Email'), ('Campaign', 'Campaign'), ('Other', 'Other')], max_length=100)),
                ('lead_source_description', models.TextField(blank=True, null=True)),
                ('opportunity_amount', models.CharField(max_length=10)),
                ('referred_by', models.CharField(max_length=100)),
                ('primary_address_street', models.CharField(max_length=255)),
                ('primary_address_postal_code', models.CharField(max_length=20)),
                ('primary_address_city', models.CharField(max_length=100)),
                ('primary_address_state', models.CharField(max_length=100)),
                ('primary_address_country', models.CharField(max_length=100)),
                ('alternate_address_street', models.CharField(max_length=255)),
                ('alternate_address_postal_code', models.CharField(max_length=20)),
                ('alternate_address_city', models.CharField(max_length=100)),
                ('alternate_address_state', models.CharField(max_length=100)),
                ('alternate_address_country', models.CharField(max_length=100)),
                ('decription', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=10)),
                ('opportunity_amount', models.CharField(max_length=10)),
                ('sales_stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Need Analysis', 'Need Analysis'), ('Value Proposition', 'Value Proposition'), ('Identifying Decision Makers', 'Identifying Decision Makers'), ('Perception Analysis', 'Perception Analysis'), ('Proposal/Price Quote', 'Proposal/Price Quote'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], max_length=100)),
                ('probability', models.CharField(max_length=10)),
                ('next_step', models.CharField(max_length=255)),
                ('expected_close_date', models.DateField()),
                ('business_type', models.CharField(choices=[('Existing Business', 'Existing Business'), ('New Business', 'New Business')], max_length=100)),
                ('lead_source', models.CharField(choices=[('Cold Call', 'Cold Call'), ('Existing Customer', 'Existing Customer'), ('Self Generated', 'Self Generated'), ('Employee', 'Employee'), ('Partner', 'Partner'), ('Public Relations', 'Public Relations'), ('Direct Mail', 'Direct Mail'), ('Conference', 'Conference'), ('Trade Show', 'Trade Show'), ('Web Site', 'Web Site'), ('Word of mouth', 'Word of mouth'), ('Email', 'Email'), ('Campaign', 'Campaign'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_api.account')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
