# Generated by Django 5.1.7 on 2025-04-07 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending Input', 'Pending Input'), ('Deferred', 'Deferred')], max_length=100)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('parent_type', models.CharField(choices=[('Account', 'Account'), ('Contact', 'Contact'), ('Task', 'Task'), ('Opportunity', 'Opportunity'), ('Bug', 'Bug'), ('Case', 'Case'), ('Lead', 'Lead'), ('Project', 'Project'), ('Project Task', 'Project Task'), ('Target', 'Target'), ('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Quote', 'Quote'), ('Product', 'Product')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tasks', to='crm_api.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
