# Generated by Django 5.1.7 on 2025-03-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_lead_opportunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='decription',
            new_name='description',
        ),
    ]
