# Generated by Django 5.1.7 on 2025-04-17 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_title', models.CharField(max_length=255)),
                ('quote_number', models.IntegerField(unique=True)),
                ('valid_until', models.DateField()),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('quote_stage', models.CharField(choices=[('Draft', 'Draft'), ('Negotiation', 'Negotiation'), ('Delivered', 'Delivered'), ('On Hold', 'On Hold'), ('Confirmed', 'Confirmed'), ('Closed Accepted', 'Closed Accepted'), ('Closed Lost', 'Closed Lost'), ('Closed Dead', 'Closed Dead')], max_length=50)),
                ('invoice_status', models.CharField(choices=[('Not Invoiced', 'Not Invoiced'), ('Invoiced', 'Invoiced')], max_length=50, null=True)),
                ('payment_terms', models.CharField(choices=[('Nett 15', 'Nett 15'), ('Nett 30', 'Nett 30'), ('Other', 'Other')], max_length=50)),
                ('payment_terms_other', models.CharField(max_length=50)),
                ('approval_issues', models.TextField(blank=True, null=True)),
                ('billing_address_street', models.CharField(max_length=255, null=True)),
                ('billing_address_city', models.CharField(max_length=100, null=True)),
                ('billing_address_state', models.CharField(max_length=100, null=True)),
                ('billing_address_postalcode', models.CharField(max_length=20, null=True)),
                ('billing_address_country', models.CharField(max_length=100, null=True)),
                ('shipping_address_street', models.CharField(max_length=255, null=True)),
                ('shipping_address_city', models.CharField(max_length=100, null=True)),
                ('shipping_address_state', models.CharField(max_length=100, null=True)),
                ('shipping_address_postalcode', models.CharField(max_length=20, null=True)),
                ('shipping_address_country', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('shipping_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_quotes', to='crm_api.account')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_quotes', to='crm_api.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_quotes', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_quotes', to='crm_api.opportunity')),
            ],
        ),
    ]
