# Generated by Django 5.1.7 on 2025-04-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0004_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='invoice_status',
            field=models.CharField(choices=[('Not Invoiced', 'Not Invoiced'), ('Invoiced', 'Invoiced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_quotes', to='crm_api.opportunity'),
        ),
    ]
