# Generated by Django 5.1.7 on 2025-04-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_alter_quote_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='industry',
            new_name='industry_type',
        ),
    ]
