# Generated by Django 5.1.7 on 2025-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0007_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Guest', 'Guest'), ('Manager', 'Manager')], default='Employee', max_length=50),
        ),
    ]
