# Generated by Django 5.1.7 on 2025-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
